=== BridgingBigData/BHS/schema/label.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://bridgingbigdata.github.io/bridgehealthschema/schema/label.schema.json",
  "title": "A classification label for Data (e.g. a JSON Document)",
  "description": "Collection of properties for expressing sharing, security, privacy and provenance parameters associated with a JSON document.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "title": "Label ID",
      "description": "A Unique URI that identifies this Label"
    },
    "compartments": {
        "type": "array",
        "items": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "sharingRestrictions": {
      "type": "array",
      "title": "Sharing classification",
      "description": "Sharing Classification of the Data",
      "items": {
        "type": "string",
        "enum": [
          "Intellectual Property",
          "Internal Only",
          "License Required",
          "Public Domain",
          "No Classification"

        ]
      }
    },
    "license": {
      "type": "string",
      "title": "License",
      "description": "A license document that applies to this content, typically indicated by URL."
    },
    "copyrightHolder": {
      "type": "string",
      "title": "Copyright holder",
      "description": "The party holding the legal copyright to the JSON document."
    },
    "classification": {
      "type": "array",
      "title": "Security and Privacy Classifications",
      "description": "Security and Privacy Classification of the Data.",
      "items": {
        "type": "string",
        "enum": [
          "Homeland Security Sensitive",
          "Personally Identifiable Information",
          "Statutory Notification Requirement",
          "Restricted Data",
          "Need-to-know Requirement",
          "No Classification"
        ]
      }
    },
    "provenance": {
      "type": "object",
      "title": "Provenance",
      "description": "Describe the Provenance of the JSON document",
      "properties": {
        "narrative": {
          "type": "string",
          "title": "Narrative for the Provenance",
          "description": "Describes the workflow involved in collecting and filtering (or cleaning) the data. This could be a link to someplace that describes the data provenance. Recommended information includes how the data was collected, from where, by whom, and using what applications/scripts/etc. Is not required; is not repeatable. If unknown, unclear or not applicable write No Assertion."
        },
        "creators": {
          "type": "array",
          "title": "Creators",
          "description": "Creators of the JSON document.",
          "items": {
            "type": "object",
            "description": "A list of creators",
            "properties": {
              "name": {
                "type": "string",
                "title": "Name",
                "description": "Person, organization or device with a role in producing the JSON document. Is required. Is repeatable. Enter as First name Last name. If unknown, unclear or not applicable write No Assertion."
              },
              "email": {
                "type": "string",
                "title": "Email",
                "description": "An explanation about the purpose of this instance."
              }
            }
          }
        }
      }
    }
  },
  "additionalProperties": false
}

=== BridgingBigData/BHS/schema/label.json
{
	"id": "uri:507f1f77bcf86cd799439011",
	"license": "https://opendatacommons.org/licenses/pddl/1.0/",
	"copyrightHolder": "Company A",
	"provenance": {
		"narrative": "This information was collected by a UAV",
		"creators": [
			{
				"name": "Robin Gandhi",
				"email": "test@test.com"
			}
		]
	},
	"classification": [
		"Restricted Data"
	],
	"sharingRestrictions": [
		"Intellectual Property",
		"License Required"
	]
}
