=== BridgingBigData/BHS/schema/spall.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://bridgingbigdata.github.io/bridgehealthschema/schema/spall.schema.json",
  "title": "Spall",
  "description": "A concrete spall deficiency on bridges",
  "type": "object",
  "properties": {
    "deficiencyName": {
      "type": "string",
      "description": "Name of the Deficiency"
    },
    "structureNumber": {
        "type": "string",
        "description": "A uri that uniquely identifies a bridge structure",
        "format": "uri"
    },
    "mediaURLs": {
      "type": "array",
      "description": "URLs for media such as images and videos related to the deficiency",
      "items": {
        "type": "string",
        "description": "URL of a media item",
        "format": "uri"
      }
    },
    "onStructuralMember": {
      "type": "string",
      "description": "Structural member on which the deficiency is present"
    },
    "betweenStructuralMembers": {
      "type": "array",
      "description": "List reference structural members to locate spalls",
      "items": {
        "type": "object",
        "properties": {
          "firstStructuralMember": {
            "type": "string",
            "description": "First reference structural member"
          },
          "secondStructuralMember": {
            "type": "string",
            "description": "Second reference structural member"
          }
        }
      }
    },
    "geo": {
          "type": "object",
          "properties": {
              "coordinates": {
                  "type": "array",
                  "items": {
                      "type": "number"
                  }
              },
              "type": {
                  "type": "string"
              }
          }
    },
    "boundingBox": {
      "type": "object",
      "description": "A bounding box that includes the deficiency",
      "properties": {
        "length": {
          "type": "number",
          "description": "Length of the bounding box"
        },
        "width": {
          "type": "number",
          "description": "Width of the bounding box"
        },
        "depth": {
          "type": "number",
          "description": "depth of the deficiency in the bounding box"
        }
      },
      "required":[
        "length",
        "width"
      ]
    },
    "cause": {
      "type": "string",
      "description": "Cause of the deficiency"
    },
    "label": {
      "type": "string",
      "description": "A security, privacy and ethics label"
    }
  },
  "additionalProperties": false,
  "required":[
    "structureNumber",
    "onStructuralMember",
    "boundingBox",
    "label"
  ]
}

=== BridgingBigData/BHS/schema/spall.json
{
  "structureNumber": "C02932339",
	"deficiencyName" : "Spall 1",
  "mediaURLs": [
    "http://corinthtoday.com/wp-content/uploads/2016/02/bridge-repair.jpg"
  ],
  "onStructuralMember": "Girder",
  "geo": {
    "coordinates": [
      42.567,
      92.342
    ],
    "type": "Point"
  },
  "boundingBox": {
    "length": 5,
    "width": 6,
    "depth": 1
  },
  "label": "uri:507f1f77bcf86cd799439011"
}
